# -*- coding: utf-8 -*-
"""Most Streamed Spotify Songs of 2023 Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12bmMOaTRhD1xhQHl5Ls3wV0-NIAI8_1y

Olivia Arroyo

Most Streamed Spotify Songs of 2023 Analysis
"""

library(tidyverse)

songs <- read_csv('/content/spotify-2023.csv')

#Review the data
glimpse(songs)

duplicated(songs)

songs <- songs %>%
  mutate(streams = as.double(streams))

glimpse(songs$streams)

summary(songs)

songs <- na.omit(songs)
songs

summary(songs)

mean(songs$streams)
median(songs$streams)
sd(songs$streams)

mean(songs$in_spotify_charts)
median(songs$in_spotify_charts)
sd(songs$in_spotify_charts)

mean(songs$in_shazam_charts)
median(songs$in_shazam_charts)
sd(songs$in_shazam_charts)

ggplot(data = songs, aes(x = released_month, color = released_day)) +
  geom_jitter(aes(y = streams)) +
  labs(
    x = "Month of Release Date",
    y = "Streams",
    title = "Number of Streams for Release Dates",
    subtitle = "How do release dates impact the number of streams?",
    color = "Day of Release Date"
  )

ggplot(data = songs, aes(x = released_month)) +
  geom_histogram(bins = 12, color = "black", fill = "blue") +
  labs(
    x = "Month of Release Date",
    y = "Count",
    title = "Number of Songs Released by Month",
    subtitle = "How do release dates impact the number of streams?",

  )

danceability_perc <- songs$'danceability_%'

ggplot(data = songs, aes(x = danceability_perc)) +
  geom_point(aes(y = streams)) +
  labs(
    x = "Danceability",
    y = "Streams",
    title = "Number of Streams Based on Danceability",
    subtitle = "Is there a correlation between danceability percentage and streams?"
  )

speechiness <- songs$'speechiness_%'

ggplot(data = songs, aes(x = speechiness)) +
  geom_point(aes(y = in_shazam_charts, color = 336699), show.legend = FALSE) +
  labs(
    x = "Speechiness",
    y = "Rank in Shazam Charts",
    title = "Speechiness ",
    subtitle = "Is there a correlation between speechiness and rank in the Shazam Charts?"
  )

acousticness <- songs$'acousticness_%'
instrumentalness <- songs$'instrumentalness_%'
liveness <- songs$'liveness_%'

ggplot(data = songs, aes(x = acousticness, fill = 33333)) +
  geom_density(show.legend = FALSE) +
  labs(
    x = "Acousticness",
    y = "Density",
    title = "Acousticness Density in Top Songs"
  )

ggplot(data = songs, aes(x = instrumentalness, fill = 33333)) +
  geom_density(show.legend = FALSE) +
  labs(
    x = "Instrumentalness",
    y = "Density",
    title = "Instrumentalness in Top Songs"
  )

ggplot(data = songs, aes(x = liveness, fill = 33333)) +
  geom_density(show.legend = FALSE) +
  labs(
    x = "Liveness",
    y = "Density",
    title = "Liveness Percentage in Top Songs"
  )